name: task_chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  provider: ^6.1.4
  geolocator: ^13.0.4
  url_launcher: ^6.3.1
  supabase_flutter: ^2.8.4
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.0
  chewie: ^1.11.3
  video_player: ^2.9.5
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  # video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
